const initialTasks=[
 {id:1,title:'Brand Your E-Cell',track:'preliminary',deadline:'2026-08-18',points:75,description:'Every student community has its own identity. Define a clear vision and mission, then create a logo and tagline that help your team stand out. Your work should bring everyone together around one shared motive.'},
 {id:2,title:'Create your Social Media Presence',track:'ignite',deadline:'2026-08-25',points:125,description:'Build the foundations for a consistent online presence. Prepare a social media content plan, choose your channels, and design three example posts that introduce your community to the world.'},
 {id:3,title:'Define the roles in your team',track:'propel',deadline:'2026-09-03',points:100,description:'Map the people and responsibilities that will make your organization work. Submit a concise structure outlining every core role, ownership areas, and how the team will collaborate.'}
];
const dbKey='launchpad-tasks-v1', submissionKey='launchpad-submissions-v1';
let tasks=JSON.parse(localStorage.getItem(dbKey)||'null')||initialTasks;
let submissions=JSON.parse(localStorage.getItem(submissionKey)||'{}');
let filter='all', currentTask=null, selectedFile=null;
const $=s=>document.querySelector(s);
const formatDate=d=>new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date(d+'T12:00:00'));
function save(){localStorage.setItem(dbKey,JSON.stringify(tasks));localStorage.setItem(submissionKey,JSON.stringify(submissions));}
function render(){const visible=filter==='all'?tasks:tasks.filter(t=>t.track===filter);$('#taskGrid').innerHTML=visible.map(t=>{const sub=submissions[t.id];return `<article class="task-card"><span class="badge ${sub?'submitted':''}">${sub?'● Submitted':t.track[0].toUpperCase()+t.track.slice(1)}</span><h3>${t.title}</h3><div class="meta"><span>Deadline: ${formatDate(t.deadline)}</span><span>Points: ${sub?.grade??'—'}/${t.points}</span></div><button class="view" data-task="${t.id}">${sub?'View submission':'View details'} <span>→</span></button></article>`}).join('');$('#taskCount').textContent=`${tasks.length} open mission${tasks.length!==1?'s':''}`;const completed=Object.keys(submissions).filter(id=>tasks.some(t=>t.id==id)).length;$('#progressNumber').innerHTML=`${completed}<span>/${tasks.length}</span>`;$('#progressLine').style.width=`${tasks.length?completed/tasks.length*100:0}%`;}
function openDetail(id){currentTask=tasks.find(t=>t.id===id);selectedFile=null;const sub=submissions[id];$('#detailContent').innerHTML=`<div class="detail-hero"><span class="detail-track">${currentTask.track} track</span><h2>${currentTask.title}</h2></div><div class="detail-body"><p>${currentTask.description}</p><div class="info-grid"><div class="info">DEADLINE<b>${formatDate(currentTask.deadline)}</b></div><div class="info">MAXIMUM POINTS<b>${sub?.grade??'Not graded'} / ${currentTask.points}</b></div></div><div class="submission">${sub?`<div class="submitted-box"><b>✓ Work submitted</b>${sub.fileName} · Submitted ${sub.date}${sub.grade?` · Graded ${sub.grade}/${currentTask.points}`:''}</div><button class="primary" id="replaceBtn">Replace submission</button>`:`<h3>Submit your work</h3><label class="dropzone" for="upload"><input id="upload" type="file" accept="application/pdf" hidden><span style="font-size:30px">⇧</span><strong>Choose a PDF or drag it here</strong><span class="file-note">PDF files only · maximum 10 MB</span><span id="fileName" class="file-name"></span></label><button class="primary" id="submitBtn" disabled>Submit task <span>→</span></button>`}</div></div>`;$('#detailModal').classList.add('show');$('#detailModal').setAttribute('aria-hidden','false');const upload=$('#upload');if(upload)upload.addEventListener('change',e=>chooseFile(e.target.files[0]));const submit=$('#submitBtn');if(submit)submit.addEventListener('click',submitWork);const replace=$('#replaceBtn');if(replace)replace.addEventListener('click',()=>{delete submissions[currentTask.id];save();openDetail(currentTask.id);render();});}
function chooseFile(file){if(!file)return;if(file.type!=='application/pdf'){toast('Please choose a PDF file.');return}if(file.size>10*1024*1024){toast('That file is over the 10 MB limit.');return}selectedFile=file;$('#fileName').textContent=`Selected: ${file.name}`;$('#submitBtn').disabled=false;}
function submitWork(){if(!selectedFile)return;submissions[currentTask.id]={fileName:selectedFile.name,date:new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date()),grade:null};save();render();openDetail(currentTask.id);toast('Your work has been submitted.');}
function closeModals(){document.querySelectorAll('.modal').forEach(m=>{m.classList.remove('show');m.setAttribute('aria-hidden','true')})}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800)}
document.addEventListener('click',e=>{const v=e.target.closest('[data-task]');if(v)openDetail(+v.dataset.task);if(e.target.matches('[data-close]'))closeModals();if(e.target.closest('#adminOpen'))$('#adminModal').classList.add('show');const tab=e.target.closest('.tab');if(tab){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');filter=tab.dataset.filter;render();}});
$('#taskForm').addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));tasks.unshift({id:Date.now(),...data,points:+data.points});save();render();e.target.reset();closeModals();toast('New task published successfully.');});
render();
